name: TEST - Daily ISO Data Update & Release

on:
  push:
    branches:
      - test-workflow
  workflow_dispatch:

jobs:
  update_data_and_release:
    name: TEST - Check ISO Data, Update, and Release if Changed
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout iso-data-importer (this repo)
        uses: actions/checkout@v4
        with:
          path: importer

      - name: Checkout iso-data-open repository
        uses: actions/checkout@v4
        with:
          repository: H3xano/iso-data-open
          path: data
          token: ${{ secrets.GH_PAT_ISO_DATA_OPEN }}

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          working-directory: ./importer

      - name: Run Rake task to update data
        working-directory: ./importer
        run: |
          echo "Updating ISO data using Rake..."
          OUTPUT_PATH="${{ github.workspace }}/data"
          echo "Outputting data to: $OUTPUT_PATH"
          bundle exec rake "data:update_all[true,yaml,$OUTPUT_PATH]"
          echo "Data update task finished."

      # This is the most important step for debugging.
      - name: Check for changes, Commit and Push to iso-data-open
        id: commit_iso_data_open
        working-directory: ./data # We are inside the data repository
        run: |
          echo "--- DEBUGGING GIT STATUS ---"
          echo "Current directory: $(pwd)"
          
          echo "Listing files:"
          ls -la
          
          echo "Git status:"
          git status
          
          echo "--- END DEBUGGING ---"

          # Now, run the original logic
          if git diff --quiet HEAD; then
            echo "iso-data-open has no changes. The 'if' condition was true."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "iso-data-open has changes. The 'if' condition was false."
            git add .
            git commit -m "TEST: Update ISO open data files - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            echo "Pushing data changes to H3xano/iso-data-open..."
            git push
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      # The rest of the workflow remains the same
      - name: Bump version, Tag, and Commit in iso-data-importer
        if: steps.commit_iso_data_open.outputs.has_changes == 'true'
        working-directory: ./importer
        run: |
          echo "Data changed, proceeding with version bump..."
          bundle exec gem bump --version patch --tag --commit --push

      - name: DISABLED - Publish to RubyGems.org
        if: false
        working-directory: ./importer
        env:
          RUBYGEMS_API_KEY: ${{ secrets.METANORMA_CI_RUBYGEMS_API_KEY }}
        run: |
          echo "This step is disabled."