name: Daily ISO Data Update

on:
  schedule:
    # Runs daily at 02:00 UTC
    - cron: "0 2 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  update_data:
    name: Check for New ISO Data and Update
    runs-on: ubuntu-latest
    # No extra permissions needed, as this job only pushes to the other repo

    steps:
      - name: Checkout iso-data-importer (this repo)
        uses: actions/checkout@v4
        with:
          path: importer

      - name: Checkout iso-data-open repository
        uses: actions/checkout@v4
        with:
          # IMPORTANT: For the final PR, change this back to metanorma/iso-data-open
          repository: H3xano/iso-data-open
          path: data
          # The PAT needs write access to the data repository
          token: ${{ secrets.GH_PAT_ISO_DATA_OPEN }}

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          working-directory: ./importer

      - name: Run Rake task to update data
        working-directory: ./importer
        run: |
          echo "Updating ISO data using Rake..."
          OUTPUT_PATH="${{ github.workspace }}/data"
          bundle exec rake "data:update_all[true,yaml,$OUTPUT_PATH]"
          echo "Data update task finished."

      - name: Commit and Push Data Changes
        working-directory: ./data
        run: |
          # Check for any changes, including new files
          if [ -z "$(git status --porcelain)" ]; then
            echo "No new data found. No changes to commit."
          else
            echo "New data found. Committing changes..."
            git add .
            git commit -m "chore: Update ISO open data files"
            git push
            echo "Data changes have been pushed."
          fi